### ISSUE TITLE
aws-kafka provider not building the clusterArn parameter properly

### ISSUE THREAD

**Issue by rbrunan** [upbound/provider-aws#957]
### What happened?

I cannot create resources with the `crossplane-aws-kafka` provider, I got a 403 error talking to the AWS API, since the provider is using the role `aws-go-sdk` instead of the configured Role:
```
reading MSK Serverless Cluster (dev-awseuw1-test-1-apm): AccessDeniedException: User: arn:aws:sts::<REDACTED>:assumed-role/crossplane/aws-go-sdk-1699620053884928729 is not authorized to perform: kafka:DescribeClusterV2 on resource: dev-awseuw1-test-1-apm
```
I'm using IRSA authentication and chained assumed roles.
The provider pod is showing a backtrace in the output, anything else:
```
❯ kc logs -n crossplane provider-aws-kafka-f0108d77f033-6d847b94fd-xvlvd
{"level":"info","ts":"2023-11-10T12:40:16Z","logger":"provider-aws","msg":"Beta feature enabled","flag":"EnableBetaManagementPolicies"}
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 3546 [running]:
	>  runtime/debug.Stack()
	>  	runtime/debug/stack.go:24 +0x65
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc004f8ac00, {0xc006428900, 0x4, 0x4})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:168 +0x54
	>  github.com/go-logr/logr.Logger.WithValues(...)
	>  	github.com/go-logr/logr@v1.2.4/logr.go:323
	>  sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0xc0062f4f80)
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/builder/controller.go:402 +0x2b6
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0038eafa0, {0x4e155b0, 0xc00058e050}, {0x3d7de20?, 0xc0061eb680?})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:306 +0x18b
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0038eafa0, {0x4e155b0, 0xc00058e050})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1d9
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x85
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x587
```

Also, the error is not properly formatted:
```
Events:
  Type     Reason                         Age    From                                                          Message
  ----     ------                         ----   ----                                                          -------
  Warning  CannotObserveExternalResource  7m45s  managed/kafka.aws.upbound.io/v1beta1, kind=serverlesscluster  cannot run import: ^[[0m^[[1maws_msk_serverless_cluster.dev-awseuw1-test-1-apm-imported: Importing from ID "dev-awseuw1-test-1-apm"...^[[0m
^[[0m^[[1m^[[32maws_msk_serverless_cluster.dev-awseuw1-test-1-apm-imported: Import prepared!^[[0m
^[[0m^[[32m  Prepared aws_msk_serverless_cluster for import^[[0m
^[[0m^[[1maws_msk_serverless_cluster.dev-awseuw1-test-1-apm-imported: Refreshing state... [id=dev-awseuw1-test-1-apm]^[[0m
^[[31m^[[31m╷^[[0m^[[0m
^[[31m│^[[0m ^[[0m^[[1m^[[31mError: ^[[0m^[[0m^[[1mreading MSK Serverless Cluster (dev-awseuw1-test-1-apm): AccessDeniedException: User: arn:aws:sts::<REDACTED>:assumed-role/crossplane/aws-go-sdk-1699619600112349542 is not authorized to perform: kafka:DescribeClusterV2 on resource: dev-awseuw1-test-1-apm
^[[31m│^[[0m ^[[0m  status code: 403, request id: a972f5b4-5066-4d5a-99a9-6a7e33140a7b^[[0m
^[[31m│^[[0m ^[[0m
^[[31m│^[[0m ^[[0m^[[0m
^[[31m╵^[[0m^[[0m
^[[0m^[[0m
: import failed
```
### How can we reproduce it?

I've tried to deploy a serverless Kafka cluster observe only resource in AWS with the following configs:

```
Name:         provider-aws-kafka
Namespace:
Labels:       app.kubernetes.io/component=crossplane-provider
API Version:  pkg.crossplane.io/v1
Kind:         Provider
Metadata:
  Creation Timestamp:  2023-11-08T15:35:24Z
  Generation:          1
  Resource Version:    33139716
  UID:                 794a273c-6852-4999-8036-97861fa6b99a
Spec:
  Controller Config Ref:
    Name:                         controller-config-aws
  Ignore Crossplane Constraints:  false
  Package:                        xpkg.upbound.io/upbound/provider-aws-kafka:v0.43.1
  Package Pull Policy:            IfNotPresent
  Revision Activation Policy:     Automatic
  Revision History Limit:         1
  Skip Dependency Resolution:     false
---
Name:         controller-config-aws
Namespace:
Labels:       <none>
Annotations:  argocd.argoproj.io/sync-wave: 5
              eks.amazonaws.com/role-arn: arn:aws:iam::<CROSSPLANE ROLE>
API Version:  pkg.crossplane.io/v1alpha1
Kind:         ControllerConfig
Metadata:
  Creation Timestamp:  2023-09-27T06:38:38Z
  Generation:          7
  Resource Version:    33132480
  UID:                 9c7b13ac-8c80-4c36-9408-8305cf36a660
Spec:
  Args:
    --enable-management-policies
  Metadata:
    Labels:
      app.kubernetes.io/name:     xp-aws-provider
      app.kubernetes.io/version:  0.43.1
      co.elastic.hints/package:   prometheus
      co.elastic.hints/period:    30s
      co.elastic.hints/port:      8080
  Pod Security Context:
    Fs Group:  2000
```
The resource used is:
```
Name:         dev-awseuw1-test-1-apm-imported
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-name: dev-awseuw1-test-1-apm
API Version:  kafka.aws.upbound.io/v1beta1
Kind:         ServerlessCluster
Metadata:
  Creation Timestamp:  2023-11-10T12:48:27Z
  Generation:          1
  Resource Version:    33149959
  UID:                 4ce80d70-9dc4-46b6-b091-5f3ba91c31a2
Spec:
  Deletion Policy:  Delete
  For Provider:
    Region:  eu-west-1
  Management Policies:
    Observe
  Provider Config Ref:
    Name:  esp-dev-euw1-cp-app-1-aws-provider-config
---
Name:         esp-dev-euw1-cp-app-1-aws-provider-config
Namespace:
Labels:       crossplane.io/claim-name=esp-dev-euw1-cp-app-1
              crossplane.io/claim-namespace=mki-claims
              crossplane.io/composite=esp-dev-euw1-cp-app-1-4zs8m
Annotations:  <none>
API Version:  aws.upbound.io/v1beta1
Kind:         ProviderConfig
Metadata:
  Creation Timestamp:  2023-11-08T12:09:22Z
  Finalizers:
    in-use.crossplane.io
  Generation:        1
  Resource Version:  33143840
  UID:               f891fcf5-a377-4125-8b29-ab72adf0c1d3
Spec:
  Assume Role Chain:
    Role ARN:  arn:aws:iam::<CROSSPLANE-ROLE>-cross-account-resources
    Role ARN:  arn:aws:iam::<CROSSPLANE ROLE>
 Credentials:
    Source:  IRSA
```

### What environment did it happen in?

* Crossplane Version: v1.13.2
* Provider Version: v0.43.1
* Kubernetes Version: v1.26.1
* Kubernetes Distribution:  EKS

**Comment by chlunde** [comment]
@rbrunan 
> I cannot create resources with the `crossplane-aws-kafka` provider, I got a 403 error talking to the AWS API, since the provider is using the role `aws-go-sdk` instead of the configured Role:
`reading MSK Serverless Cluster (dev-awseuw1-test-1-apm): AccessDeniedException: User: arn:aws:sts::<REDACTED>:assumed-role/crossplane/aws-go-sdk-1699620053884928729 is not authorized to perform: kafka:DescribeClusterV2 on resource: dev-awseuw1-test-1-apm`

I believe the error shows that `crossplane` is the _role name_ and `aws-go-sdk-1699620053884928729` is the _session name_. If the role name was wrong it would fail earlier when attempting to assume the role. Have you checked the IAM permissions of the role?

**Comment by rbrunan** [comment]
>I believe the error shows that crossplane is the role name and aws-go-sdk-1699620053884928729 is the session name. If the role name was wrong it would fail earlier when attempting to assume the role. Have you checked the IAM permissions of the role?

Thank you for your answer, @chlunde. You are right, the role used is fine, but the bug still exists. Let me change the issue title and explain what we have found. 

We have confirmed the `crossplane` role has permissions over the resources and follow the request in the cloud trail app. There we were able to find the request parameter called `clusterArn`, which was malformed. Instead of containing the whole arn, it contains only the Kafka cluster name:

```
    "errorCode": "AccessDenied",
    "requestParameters": {
        "clusterArn": "dev-awseuw1-test-1-apm"
    },
```

We changed the external name annotation to the actual cluster ARN, and the authentication and whole sync were successful.

```
"requestParameters": {
        "clusterArn": "arn%3Aaws%3Akafka%3Aeu-west-1%3A<REDACTED>%3Acluster%2Fdev-awseuw1-test-1-apm%2Ff81e6e45-f854-4fbe-9240-127c0772f3fa-s1"
    },
```
My understanding is that the `clusterArn` parameter is not being properly constructed from the external-name when using the `observe` managed policy.

**Comment by rbrunan** [comment]
Thank you @mbbush, understood. I was misleading because the [official docs](https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/) say:
> To import an existing external resource in a Provider, create a new managed resource with the crossplane.io/external-name annotation. Set the annotation value to the name of the resource in the Provider.

I can see that this name depends on the implementation of the MR.

I think it would be great to have a more flexible method to determine the target resource in the CSP. Maybe filtering by tags and/or by consistent format names across resources would be better.

I'm going to close this issue since everything is working as expected.
